name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        crystal:
          - 1.1.1
          - 1.2.1
        include:
          - experimental: true
            crystal: nightly
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install --ignore-crystal-version
      - name: Run tests
        run: crystal spec -v --error-trace --order=random
        env:
          http_proxy: http://51.38.71.101:8080
